#!/usr/bin/env bash
#transfer file

# {$1} - IP Address web-01
# {$2} - path to ssh key
# {$3} - Username
# {$4} - Path to file file to be sent
# Ex - ./0* 0-transfer_file 	34.203.75.147 web-02 ~/.ssh...

if [ $# != 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "${4}" "${1}" "${3}"@"${2}":~/
fi
