#!/usr/bin/env bash
#Accepts a string as an argument and
#Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument pass
#Ping the IP 5 times

if [ $# -eq  0 ]
then
	"Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
