#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID, displays:
#To infinity and beyond indefinitely
#I hate the kill command when receiving a SIGTERM signal
#Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself
#when receiving a SIGQUIT or SIGTERM signal

i=0
echo "$$" > /var/run/myscript.pid

while [ $i ]; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0;' SIGTERM
	trap "rm /var/run/myscript.pid; exit 0;" SIGQUIT
done
