#!/usr/bin/env bash
#Displays To infinity and beyond indefinitely,
#swith leep 2 in between each iteration,
#I am invincible!!! when receiving a SIGTERM signal.

i=0
while [ $i ]; do
	echo "To infinity and beyond"
	sleep 2
	trp 'echo "I am invincible!!!"' SIGTERM
done
